### ISSUE TITLE
Github adapter repo is missing

### ISSUE THREAD

**Issue by manuel-mauky** [contentlab-sh/contentlab#17]
In the readme you are linking to [git-adapter-github](https://github.com/contentlab-sh/git-adapter-github).
However, this is a 404. There is no such repo, at least not public.

I'm currently trying out the github adapter and I think I found a bug but cannot report it.

**Comment by advancingu** [comment]
Very good point. I guess I never noticed that it was still a private repository. How embarrassing. Fixed now, please try again.
